version: "3.8"

services:
  backend:
    build: ./backend
    env_file:
        - ./backend/app/.env
    environment:
      PYTHONDONTWRITEBYTECODE: 1
    restart: always
    ports:
      - 8000:8000
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./backend/app/app:/app/app

  frontend:
    build:
      context: ./frontend
      target: builder
    env_file:
      - ./frontend/app/.env
    restart: always
    ports:
      - 3000:3000
    command: npm run dev -- --host --port 3000
    volumes:
      - ./frontend/app:/app
    depends_on:
      - backend
