version: "3.8"

services:
  mongo:
    image: mongo:4.4.18-rc0-focal
    env_file:
      - ./mongo/.env
    restart: always
    expose:
      - 27017
    volumes:
      - data:/data/db

  backend:
    build: ./backend
    env_file:
      - ./backend/app/.env.dev
    environment:
      PYTHONDONTWRITEBYTECODE: 1
    restart: always
    ports:
      - 8000:8000
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./backend/app/app:/app/app
    depends_on:
     - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: dev.dockerfile
    env_file:
      - ./frontend/app/.env
    restart: always
    ports:
      - 3000:3000
    command: npm run dev -- --host --port 3000
    volumes:
      - ./frontend/app:/app
    depends_on:
      - backend

volumes:
  data:
