services:
  resume_api:
    build: ./resume_api
    environment:
      - CORS_ALLOW_ORIGINS=${CORS_ALLOW_ORIGINS}
      - DB_URI=${DB_URI}
      - DB_NAME=${DB_NAME}
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_API_AUDIENCE=${AUTH0_API_AUDIENCE}
      - AUTH0_ISSUER=${AUTH0_ISSUER}
      - CLOUDINARY_URL=${CLOUDINARY_URL}
    restart: always
    ports:
      - 8000:8000

  editor:
    build:
      context: ./editor
      dockerfile: prod.dockerfile
      args:
        VITE_EDITOR_API_HTTP_URL: ${VITE_EDITOR_API_HTTP_URL}
        VITE_RENDERER_HTTP_URL: ${VITE_RENDERER_HTTP_URL}
        VITE_GENERATOR_HTTP_URL: ${VITE_GENERATOR_HTTP_URL}
        VITE_AUTH0_DOMAIN: ${VITE_AUTH0_DOMAIN}
        VITE_AUTH0_CLIENT_ID: ${VITE_AUTH0_CLIENT_ID}
        VITE_AUTH0_AUDIENCE: ${VITE_AUTH0_AUDIENCE}
    restart: always
    ports:
      - 3000:80
    depends_on:
      - resume_api

  domain:
    build:
      context: ./domain
      dockerfile: prod.dockerfile
      args:
        REPO_URL: ${REPO_URL}
        EDITOR_URL: ${EDITOR_URL}
    restart: always
    ports:
      - 80:80
