version: "3.8"

services:
  generator:
    build: ./generator
    restart: always
    ports:
      - 8001:8001

  backend:
    build: ./backend
    env_file:
      - ./backend/app/.env.prod
    restart: always
    ports:
      - 8000:8000

  frontend:
    build:
      context: ./frontend
      dockerfile: prod.dockerfile
      args:
        VITE_AUTH0_DOMAIN: ${VITE_AUTH0_DOMAIN}
        VITE_AUTH0_CLIENT_ID: ${VITE_AUTH0_CLIENT_ID}
        VITE_AUTH0_AUDIENCE: ${VITE_AUTH0_AUDIENCE}
    env_file:
      - ./frontend/app/.env
    restart: always
    ports:
      - 80:80
    depends_on:
      - backend
