version: "3.8"

services:
  mongo:
    image: mongo:4.4.18-rc0-focal
    env_file:
      - ./mongo/.env
    restart: always
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
      - ./mongo/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh

  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    env_file:
      - ./mongo-express/.env
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo

  browser:
    build:
      context: ./browser
    restart: always
    ports:
      - 3030:3000

  renderer:
    build: ./renderer
    env_file:
      - ./renderer/.env
    environment:
      PYTHONDONTWRITEBYTECODE: 1
    restart: always
    ports:
      - 8001:8001
    command: pipenv run dev
    volumes:
      - ./renderer/app/:/app/app
    depends_on:
      - mongo

  generator:
    build: ./generator
    env_file:
      - ./generator/.env
    environment:
      PYTHONDONTWRITEBYTECODE: 1
    restart: always
    ports:
      - 8002:8000
    command: pipenv run dev --host 0.0.0.0
    volumes:
      - ./generator/app/:/app/app
    depends_on:
      - browser
      - renderer

  resume_api:
    build: ./resume_api
    env_file:
      - ./resume_api/.env
    environment:
      PYTHONDONTWRITEBYTECODE: 1
    restart: always
    ports:
      - 8000:8000
    command: pipenv run dev --host 0.0.0.0
    volumes:
      - ./resume_api/app:/app/app
    depends_on:
      - mongo

  domain:
    build:
      context: ./domain
      dockerfile: dev.dockerfile
    env_file:
      - ./domain/.env
    restart: always
    ports:
      - 80:3000
    volumes:
      - ./domain:/app

volumes:
  data:
