version: "3.8"

services:
  generator:
    build: ./generator
    environment:
      DB_URI: ${DB_URI}
    restart: always
    expose:
      - 8001

  backend:
    build: ./backend
    environment:
      ALLOW_ORIGINS: ${ALLOW_ORIGINS}
      DOMAIN: ${DOMAIN}
      API_AUDIENCE: ${API_AUDIENCE}
      ISSUER: ${ISSUER}
      ALGORITHMS: ${ALGORITHMS}
      DB_URI: ${DB_URI}
      CLOUDINARY_URL: ${CLOUDINARY_URL}
    restart: always
    ports:
      - 8000:8000

  frontend:
    build:
      context: ./frontend
      dockerfile: prod.dockerfile
      args:
        VITE_AUTH0_DOMAIN: ${VITE_AUTH0_DOMAIN}
        VITE_AUTH0_CLIENT_ID: ${VITE_AUTH0_CLIENT_ID}
        VITE_AUTH0_AUDIENCE: ${VITE_AUTH0_AUDIENCE}
    restart: always
    ports:
      - 80:80
    depends_on:
      - backend
      - generator

  frontend:
    build:
      context: ./domain
      dockerfile: prod.dockerfile
      args:
        REPO_URL: ${REPO_URL}
        EDITOR_URL: ${EDITOR_URL}
    restart: always
    ports:
      - 81:80
