version: "3.8"

services:
  backend:
    build: ./backend
    env_file:
        - ./backend/app/.env
    restart: always
    ports:
      - 8000:8000

  frontend:
    build: ./frontend
    env_file:
      - ./frontend/app/.env
    restart: always
    ports:
      - 80:80
    depends_on:
      - backend
