services:
  editor:
    build:
      context: ./editor
      dockerfile: prod.dockerfile
      args:
        VITE_EDITOR_API_HTTP_URL: ${VITE_EDITOR_API_HTTP_URL}
        VITE_RENDERER_HTTP_URL: ${VITE_RENDERER_HTTP_URL}
        VITE_GENERATOR_HTTP_URL: ${VITE_GENERATOR_HTTP_URL}
        VITE_AUTH0_DOMAIN: ${VITE_AUTH0_DOMAIN}
        VITE_AUTH0_CLIENT_ID: ${VITE_AUTH0_CLIENT_ID}
        VITE_AUTH0_AUDIENCE: ${VITE_AUTH0_AUDIENCE}
    restart: always
    ports:
      - 3000:80

  domain:
    build:
      context: ./domain
      dockerfile: prod.dockerfile
      args:
        REPO_URL: ${REPO_URL}
        EDITOR_URL: ${EDITOR_URL}
    restart: always
    ports:
      - 80:80
